Add Grid components
cboard-org/cboard-ai-builder pull request #35
Opened 2024-01-29 20:21 UTC by RodriSanchez1

This pull request adds the Grid components to the project. The Grid components include the Board component, the Row component, the DraggableItem component, and the DroppableCell component. These components are essential for creating a grid-based layout and implementing drag-and-drop functionality. The pull request also includes the necessary dependencies for the Grid components, such as react-dnd and react-dnd-touch-backend.

2024-01-29 20:23 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@board/FixedGrid/utils.ts
> +//TODO refactor to avoid using any
Add tech debt issue

2024-02-07 16:54 UTC, maxicapodacqua requested changes
Some commented code that needs to be cleaned up

2024-02-07 16:54 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/gridManipulation.ts
> +// }
Consider removing commented code

2024-02-07 16:54 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/keysDetection.ts
> +//TODO: Refactor this file to add keys detection to the grid
Do we need this file at all?

2024-02-07 16:54 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/DroppableCell/DroppableCell.tsx
> +  });
I wasn't familiar with `classNames` npm package, but I think this can be replaced by using data attributes instead of joining CSS classes. I kinda think it shouldn't be necessary to install a package to this these type of tasks.
For example:
```ts
<div id={id} className={`${styles.root} ${className}` }  data-isActive={isActive} ref={drop}>
```
Then in your styles you can do:
```css
.root[data-isActive=true]{
//...
}
```

This is also beneficial for future testing

2024-02-08 17:23 UTC, maxicapodacqua approved these changes
Code looks good, just added some minor comments, feel free to merge

2024-02-08 17:23 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/BoardContainer.tsx
> +          rows={board.grid ? board.grid.rows : 6} // DEFAULT_ROWS_NUMBER}
Consider adding these constants somewhere (maybe in this file or a separate file called constants.ts

2024-02-08 17:23 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/DraggableItem/DraggableItem.tsx
> +  className?: string;
Remove unused prop

2024-02-08 17:23 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/Grid.tsx
> +'use client';
Does this need to be a client component?

2024-02-08 17:23 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/Grid.tsx
> +  const grid = utils.sortGrid({ columns, rows, order, items });
Have you tried using `useMemo` here? Just curious to see if this could improve performance

2024-02-08 17:23 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Grid/Row/Row.tsx
> +}
There is a react type you can use in these cases called `React.PropsWithChildren`, you can replace all of these with just:
```suggestion

function Row({ children }: React.PropsWithChildren) {
  return <div className={styles.root}>{children}</div>;
}
```

2024-02-08 17:34 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@board/Grid/Grid.tsx
> +'use client';
Yes, because of the use of the drag and drop funtionality

2024-02-08 17:44 UTC, merged