Feature/history and saved boards component
cboard-org/cboard-ai-builder pull request #39
Opened 2024-02-06 00:01 UTC by tomivm

This PR is the first step to updating the UI to the last design. Also, the component History item is replaced by a new one called DataItem to reuse it for the saved boards.
 Related to #38

2024-02-06 04:26 UTC, maxicapodacqua requested changes
Move shared component to higher directory structure `/src/components/...`

2024-02-06 04:26 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/savedData/DataItem.tsx
If this is going to be a component to be used in different areas of the app, I think it should be in a new directory, lets say: `src/components`, maybe create a folder for this specific component only

2024-02-06 04:26 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/savedData/types.ts
> +};
Are both History and Saved Boards going to have a date field?
Maybe instead of creating a data type you can use a Generic type and then when we render we can let TS know what entity we are trying to create a ListItem for. I'll add an example in another part of the code...

2024-02-06 04:26 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/savedData/DataItem.tsx
> +  );
This code assumes that both History and Saved Boards are the same entity (which can be true). You can made this more generic with an extra type parameter:
```ts
type Props<DataType> = {
  data: DataType;
  onDelete: (dataRow: DataRow) => void;
};
```

```ts
export default function DataItem<DataType>({ data, onDelete }: Props<DataType>) {
```

That way you can do something like this:
```
const someOtherEntity = new User(...);
<DataItem<User>
          data={someOtherEntity }
          onDelete={() => deleteUserData(someOtherEntity )}
        />
```

Or if you want to render a saved board:
```
const savedBoards= new SavedBoards(...);
<DataItem<SavedBoards>
          data={savedBoards}
          onDelete={() => deleteSavedBoards(savedBoards)}
        />
```
Just making sure those types has the needed fields to render a data item (id and date I think?? ).

Anyways, I would consider this minor at this point in development, feel free to try this out or leave it for later

2024-02-06 21:31 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@history/HistoryList.tsx
>  import HistoryItem from './HistoryItem';
Remove HistoryItem import

2024-02-06 21:38 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/layout.tsx
>  import Typography from '@mui/material/Typography';
Remo Typography import

2024-02-07 15:44 UTC, maxicapodacqua requested changes
Build isn't passing
```➜  cboard-ai-builder git:(3a6b927) yarn build
yarn run v1.22.21
$ next build
   ▲ Next.js 14.0.4

 ✓ Creating an optimized production build
 ✓ Compiled successfully

Failed to compile.

./src/components/savedData/DataItem.tsx
6:10  Error: 'DataRow' is defined but never used.  @typescript-eslint/no-unused-vars

./src/components/savedData/Selector.tsx
6:8  Error: 'Typography' is defined but never used.  @typescript-eslint/no-unused-vars
7:8  Error: 'List' is defined but never used.  @typescript-eslint/no-unused-vars

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2024-02-07 16:26 UTC, RodriSanchez1 commented on src/components/savedData/Selector.tsx
> +        <Tab label="Saved" />
Use messages from intl

2024-02-07 19:57 UTC, merged