Feature/reusable pagination on SavedData
cboard-org/cboard-ai-builder pull request #45
Opened 2024-02-10 01:30 UTC by tomivm

2024-02-15 01:02 UTC, RodriSanchez1 requested changes

2024-02-15 03:58 UTC, maxicapodacqua requested changes

2024-02-15 03:58 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@savedBoards/SavedBoardList.tsx
> +  return <DataList list={histories} deleteItem={deleteSavedBoardsData} />;
Rename all `histories` variables to a more meaningful name (savedBoards?)

2024-02-15 03:58 UTC, maxicapodacqua commented on src/components/DataList/DataList.tsx
> +};
Consider adding `satisfies Record<string, SxProps>` to insure types

2024-02-15 03:58 UTC, maxicapodacqua commented on src/components/DataList/DataList.tsx
> +  const itemsPerPage = 2;
Consider creating a global constant for this, I used upper-cased constants in a separate file (like constants.ts) in my current branch

2024-02-16 00:51 UTC, tomivm commented on src/app/[locale]/dashboard/@savedBoards/actions.ts
> +  // Here we query DB
It was resolved Using the error.js file convention. Please show me how to add the translations to it. @RodriSanchez1

2024-02-19 20:44 UTC, RodriSanchez1 commented on src/components/ErrorAndReset/Styles.ts
Change file name to `styles.ts`

2024-02-19 20:46 UTC, RodriSanchez1 commented on src/components/ErrorAndReset/ErrorAndReset.tsx
> +      Something went wrong getting your data!
Use intl library for the messages.

2024-02-19 20:46 UTC, RodriSanchez1 commented on src/components/DataList/Styles.ts
Change name to `styles.ts`

2024-02-20 01:13 UTC, tomivm commented on src/components/ErrorAndReset/ErrorAndReset.tsx
> +      Something went wrong getting your data!
Please abord this in a different PR 
Issue: https://github.com/cboard-org/cboard-ai-builder/issues/54

2024-02-21 15:54 UTC, merged