Creates UI for signIn page integrating with OAuth
cboard-org/cboard-ai-builder pull request #49
Opened 2024-02-15 15:27 UTC by maxicapodacqua

Closes #11 

Things to fix in future iterations:
1. Layout spaces (some padding might not match design)
2. Mobile is not including the image at the bottom
3. Privacy and Terms links are not going to any page and their location is incorrect, should be at the bottom of the page

Features:
* When user is not logged in, the app will redirect them to the signin/ page
* After login they will be redirected to the dashboard (or any callbackURL they had)
* Login Dialog allows for email/password login
* OAuth buttons allows for login with Google/Facebook/Apple login
* Error messages are shown as MUI Alert components

2024-02-15 22:25 UTC, RodriSanchez1 commented on src/app/[locale]/signin/Container.tsx
> +            <Image
We need to add a felixble image container

2024-02-20 00:09 UTC, tomivm commented
The web console is showing these errors
`Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(Box)`, expected a ReactNode.`
`Warning: Extra attributes from the server: data-new-gr-c-s-check-loaded,data-gr-ext-installed`

2024-02-20 14:54 UTC, maxicapodacqua commented
> Warning: Extra attributes from the server: data-new-gr-c-s-check-loaded,data-gr-ext-installed

That warning it's[ because of the Gramarly extension](https://stackoverflow.com/questions/75337953/what-causes-nextjs-warning-extra-attributes-from-the-server-data-new-gr-c-s-c) (I have the same warning and extension installed) .

I'll work on the ForwardRef warning now

2024-02-21 15:59 UTC, tomivm requested changes

2024-02-21 15:59 UTC, tomivm commented on src/app/[locale]/signin/Container.tsx
Please Avoid using the name 'Container' for the files. you could use the name of the component. like 'Signin'

2024-02-21 16:30 UTC, merged