Feature - Add Tile and Symbol components
cboard-org/cboard-ai-builder pull request #52
Opened 2024-02-19 21:32 UTC by RodriSanchez1

This pull request adds the Tile and Symbol components to the project. The Tile component is responsible for rendering a tile with a shape and an optional symbol, while the Symbol component displays an image and a label.

2024-02-20 15:35 UTC, maxicapodacqua requested changes

2024-02-20 15:35 UTC, maxicapodacqua commented on src/components/SelectTileMask/SelectTileMask.tsx
> +  };
Move this to a styles.ts file

2024-02-20 15:35 UTC, maxicapodacqua commented on src/components/SelectTileMask/SelectTileMask.tsx
> +    CheckCircle: {
Start name with lower case

2024-02-20 15:35 UTC, maxicapodacqua commented on src/components/Symbol/Symbol.tsx
> +      {labelpos === 'Above' && (
If the value of `labelpos` can be 'Above' or 'Below', consider using an enum or a union type instead of a string:
```ts
type Props = {
  label: string | undefined;
  labelpos: "Above" | "Below" | undefined;
  image: string | undefined;
};
```

2024-02-20 15:35 UTC, maxicapodacqua commented on src/components/Tile/Tile.tsx
> +  const isFolder = variant === 'folder';
Could this be simplified? `variant` is only being used in this context, maybe to something like:
```ts
const isFolder = Boolean(tile.loadBoard);
```

2024-02-22 21:06 UTC, tomivm commented on src/components/SelectTileMask/index.ts
I don't know why this file is used. can you explain me, please?

2024-02-22 21:39 UTC, tomivm commented on src/app/[locale]/dashboard/@board/Toolbar.tsx
> +      <IconButton onClick={() => onEditClick()}>
Only as a comment.
you could pass the prop directly like `<IconButton onClick={onEditClick}>`

2024-02-22 21:46 UTC, tomivm commented on src/components/Symbol/Symbol.tsx
> +          {/* TODO: Use Image component from next to optimize images - TechDebt */}
Create an issue

2024-02-22 21:48 UTC, tomivm commented on src/components/Tile/Tile.tsx
> +  } as { labelPosition: LabelPositionRecord }; // TODO: get from settings
Create an issue

2024-02-27 02:28 UTC, RodriSanchez1 commented on src/components/SelectTileMask/index.ts
The index.js files are there to provide easy entry points for components. Even though they add noise, they simplify imports. 

See [link] (https://stackoverflow.com/a/44092481/21537109)

2024-02-27 02:34 UTC, merged