Feature/add zustand store for prompt store
cboard-org/cboard-ai-builder pull request #57
Opened 2024-02-22 20:53 UTC by tomivm

Used this doc https://docs.pmnd.rs/zustand/guides/nextjs

This setup is more complex than the normal use of zustand. 
@maxicapodacqua @RodriSanchez1 
Do you think that is useful and a good Idea?

A bunch of changes are only to use a new structure for the prompt property.

2024-02-22 21:33 UTC, maxicapodacqua requested changes

2024-02-22 21:33 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@savedBoards/actions.ts
> +  };
You are duplicating this type between `src/app/[locale]/dashboard/@history/actions.ts`, consider creating a Prompt type in a different file

2024-02-22 21:33 UTC, maxicapodacqua commented on src/providers/prompt-store-provider.tsx
> +}
Use `type` instead of `interface`

2024-02-22 21:33 UTC, maxicapodacqua commented on src/providers/prompt-store-provider.tsx
> +}
You can use `React.PropsWithChildren` instead of a different type here

2024-02-22 21:33 UTC, maxicapodacqua commented on src/providers/prompt-store-provider.tsx
> +export const usePromptStore = <T,>(selector: (store: PromptStore) => T): T => {
Use a more meaningful name for you generics `T`, I'm not sure what is it used for here

2024-02-22 21:33 UTC, maxicapodacqua commented on src/stores/prompt-store.ts
> +  colorScheme: string;
If the `colorScheme` only accept some values use a union type:
```ts
colorScheme: 'fitzgerald' | 'something-else' | 'foo'
```

2024-02-22 21:33 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
> +  }, [prompt]);
Do we need this `useEffect`?

2024-02-22 22:35 UTC, tomivm commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
> +  }, [prompt]);
I think we only should change the rendered values for the prompt when the edit button or the example button is clicked. what do you mean? @maxicapodacqua

2024-02-23 03:06 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
> +  }, [prompt]);
Why do you need to add this `useEffect`? This only has a console log

2024-02-23 20:35 UTC, tomivm commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
> +  }, [prompt]);
It's for Showing the values to the user on the prompt component. I will create an issue and separate the work for another PR.

2024-02-25 22:59 UTC, shayc commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
>  import { useFormState } from 'react-dom';
nit: can be imported as:

```ts
import { useFormState, useFormStatus } from 'react-dom';
```

2024-02-25 22:59 UTC, shayc commented on src/stores/prompt-store.ts
> +  usePictonizer: boolean;
`usePictonizer` is a confusing name for a `boolean` value in React.
React has a naming convention for hooks that start with a `use` prefix.

A better name would be `shouldUsePictonizer`.

Examples:

* `is`: Used to denote a boolean value, often indicating the state of an object or condition. For example, `isActive`, `isLoggedIn`, `isEmpty`.
* `has`: Suggests possession or inclusion, used for variables that check for the existence of something. Examples include `hasChildren`, `hasErrors`, `hasAccess`.
* `can`: Implies permission or capability, used for variables that represent whether an action is possible. Examples: `canEdit`, `canDelete`, `canView`.
* `should`: Indicates a recommendation or potential action, often used in scenarios involving conditional logic. For example, `shouldRefresh`, `shouldRetry`, `shouldUpdate`.

2024-02-25 22:59 UTC, shayc commented on src/app/[locale]/dashboard/types.ts
> +export type Prompt = {
What's the difference between `Prompt` and `PromptState` types?

2024-02-25 22:59 UTC, shayc commented on src/components/DataItem/DataItem.tsx
> +          <IconButton onClick={() => onEdit()} size="small">
`IconButton` should have an `aria-label` attribute to make them accessible to screen readers.

Something like:

```ts
<IconButton aria-label="Edit" onClick={() => onEdit()} size="small">
<IconButton aria-label="Delete" onClick={() => onDelete(data)} size="small">
```

2024-02-25 22:59 UTC, shayc commented on src/components/DataItem/DataItem.tsx
>                whiteSpace: 'nowrap',
In my experience, you want to keep JSX small and clean, without implementation details like this object, that tends to grow as the application changes.

I would save it to a variable:

```ts
const primaryTypographyProps = {
  style: {
    ...
  }
};
...

<ListItemText
  primary={description}
  primaryTypographyProps={primaryTypographyProps}
  ...
```

2024-02-25 22:59 UTC, shayc commented on README.md
> +For the manage of the state we use [Zustand](https://docs.pmnd.rs/zustand/getting-started/introduction) folowing [this Article](https://docs.pmnd.rs/zustand/guides/nextjs).
Some grammatical fixes:

To manage state, we use [Zustand](https://docs.pmnd.rs/zustand/getting-started/introduction) following the guidelines provided in [this article](https://docs.pmnd.rs/zustand/guides/nextjs).

2024-02-25 22:59 UTC, shayc commented on README.md
> +Take care about this recomendations:
Grammatical fixes (thanks to ChatGPT)

Please consider these recommendations:

- Avoid Global Stores: The store should not be shared across requests and, therefore, must not be defined as a global variable. It is recommended to create a store for each request to ensure isolation and prevent unintended data sharing.

- React Server Components and Store Interaction: React Server Components (RSCs) should neither read from nor write to the store. RSCs are not designed to use hooks or context, as they are intended to be stateless. Interacting with a global store from an RSC violates the architectural principles of Next.js.

2024-02-25 22:59 UTC, shayc commented on src/app/[locale]/dashboard/types.ts
> +  colorScheme: 'fitzgerald' | 'something-else' | 'foo';
should remove `something-else` and `foo` and replace with real color schemes :)

2024-02-28 22:00 UTC, tomivm commented on src/components/DataItem/DataItem.tsx
>                whiteSpace: 'nowrap',
Thanks Shay! I will open a ticket requesting these changes. #64

2024-02-28 22:16 UTC, tomivm commented on src/app/[locale]/dashboard/types.ts
> +export type Prompt = {
are the same!! thanks!

2024-02-28 23:13 UTC, RodriSanchez1 approved these changes

2024-02-28 23:13 UTC, merged