Feature/improve examples text areas
cboard-org/cboard-ai-builder pull request #60
Opened 2024-02-27 01:32 UTC by tomivm

2024-02-27 15:38 UTC, maxicapodacqua requested changes

2024-02-27 15:38 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@board/Styles.ts
Rename file to be lower case `styles.ts`

2024-02-27 16:19 UTC, RodriSanchez1 requested changes
I get this view:
![image](https://github.com/cboard-org/cboard-ai-builder/assets/80465873/c4f374c4-b22c-4316-b6da-24ebe420db06)

I think we can do it better... The scroll bars are also not working.
Im thinking on avoid using an TextArea for the messages. Just create our component for that. Let me know what do you think

2024-02-28 00:27 UTC, tomivm commented
@RodriSanchez1 I was using the InitialContent from the BoardContainer. To use it from the page of the @board Now I convert the component to a a client component.

2024-02-28 01:06 UTC, merged