Feature - Add mongoose
cboard-org/cboard-ai-builder pull request #69
Opened 2024-03-01 15:08 UTC by RodriSanchez1

2024-03-01 15:11 UTC, maxicapodacqua commented on src/db/dbConnect.ts
Move this file to /lib as it a wrapper of an external dependency

2024-03-01 15:13 UTC, maxicapodacqua commented on src/db/services/Board/controller.ts
Consider using the repository pattern instead of a controller as we are not doing MVC in this project.
This could be good inspiration:
https://medium.com/@technorahmon/building-a-robust-repository-layer-with-next-js-14-and-mongodb-a-comprehensive-guide-153de0b6b334

2024-03-02 16:33 UTC, tomivm commented on src/lib/dbConnect.ts
> +  var mongoose: {
could you use let?

2024-03-02 17:55 UTC, tomivm commented on src/db/services/Board/model.ts
> +});
Consider open an issue to use a package like https://www.npmjs.com/package/mongoose-tsgen to mage types on typescript and on mongoose

2024-03-02 18:01 UTC, tomivm commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    console.log('response', response);
remember remove log

2024-03-02 18:32 UTC, tomivm commented on src/db/services/Board/model.ts
> +const BoardSchema = new mongoose.Schema<Board>({
Should be good to Save the Prompt ID

2024-03-02 18:38 UTC, tomivm requested changes

2024-03-02 18:38 UTC, tomivm commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    const response = await create(board);
Don't save the Board on submit. Only save the Prompt or update the history of the user

2024-03-08 15:43 UTC, RodriSanchez1 commented on src/lib/dbConnect.ts
> +  var mongoose: {
nop, the  [oficial nextjs mongoose example](https://github.com/vercel/next.js/blob/31a3aff75534378e277331b4e0a996995c49e269/examples/with-mongodb-mongoose/lib/dbConnect.ts#L3) says

``` javascript
var mongoose: any; // This must be a var and not a let / const
```

2024-03-08 16:19 UTC, RodriSanchez1 commented on src/db/services/Board/model.ts
> +});
Done. See #85

2024-03-08 17:19 UTC, tomivm commented on src/lib/dbConnect.ts
> +  var mongoose: {
Perfect! thanks

2024-03-15 01:59 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
Tech debt  issue created 
#110

2024-03-15 13:49 UTC, maxicapodacqua requested changes

2024-03-15 13:49 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
Are you sure we need to add this validation here? The middleware should be handling this by default, do you have a way to reproduce this error?

2024-03-15 13:49 UTC, maxicapodacqua commented on src/db/services/Board/model.ts
> +import { TileRecord } from '@/components/Tile/types';
Consider moving these types to a different more general location as this is coupling the components and pages with the db.
You can create these types at this level and then import those in the dashboard or tiles.
Think of this as: if the database schema changes, do I need to change the UI? probably no

2024-03-15 13:49 UTC, maxicapodacqua commented on src/db/services/Board/model.ts
> +    required: [true, 'Please provide a userId for this board.'],
Add internationalization to these messages, unless they are for backend use only

2024-03-15 13:49 UTC, maxicapodacqua commented on src/db/services/Prompt/model.ts
> +};
Same here, avoid coupling UI with DB layer

2024-03-15 21:29 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
You are right! I will remove it

2024-03-15 21:36 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
_In contrast to useSession, which will return a session object whether or not a user has logged in (whether or not cookies are present), getServerSession only returns a session object when a user has logged in (only when authenticated cookies are present), otherwise, it returns null._ from [getServerSession next oAuth docs](https://next-auth.js.org/configuration/nextjs#in-app-router)

2024-03-15 21:38 UTC, RodriSanchez1 commented on src/db/services/Board/model.ts
> +    required: [true, 'Please provide a userId for this board.'],
We can avoid it for now. Im not sure if we will show this errors messages to the users

2024-03-15 21:47 UTC, RodriSanchez1 commented on src/db/services/Board/model.ts
> +import { TileRecord } from '@/components/Tile/types';
Ok! I will fix it in other PR. See #114

2024-03-16 18:01 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
You can throw an exception, unless you want to capture this specific use case in the UI. But I don't think that's going to happen as this might not be reproducible.
Do you have a way to reproduce the session being `null` there?

2024-03-16 18:03 UTC, maxicapodacqua commented on src/db/services/Board/model.ts
> +    required: [true, 'Please provide a userId for this board.'],
Should we remove these validation errors then? Just to avoid confusion from future contributors.

2024-03-16 18:55 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
No, I couldn't reproduce it. Probably never get it. So you recommend thrown an exception instead?

2024-03-16 19:02 UTC, maxicapodacqua commented on src/app/[locale]/dashboard/@promptForm/actions.tsx
> +    return { error: { message: 'Failed to get session, please log in' } }; //redirect to login
Yeah, this is more of a runtime error. If it happens we should expect the server to fail. We can create an error page (if it ever happens) for the user

2024-03-18 13:04 UTC, tomivm commented on src/db/services/Board/model.ts
> +import { TileRecord } from '@/components/Tile/types';
@RodriSanchez1  please could you fix that in this PRs or merge this and fix it. I need to move the entire 'dashboard' UI folder and this can cause errors

2024-03-18 15:58 UTC, merged