Feature/animate prompt value change
cboard-org/cboard-ai-builder pull request #71
Opened 2024-03-01 18:25 UTC by tomivm

Show updated prompt values on edit click and example click
close #70

2024-03-05 03:05 UTC, RodriSanchez1 requested changes

2024-03-05 03:05 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
> +                inputProps={{ minLength: 5, maxLength: 60 }}
All the examples have more than 60 characters. If you increase this value, will note an unexpected behaviour when try to modify the prompt text area. 
We can leave the user freely modify the text or avoid it. What do you think about this?

2024-03-05 03:05 UTC, RodriSanchez1 commented on src/app/[locale]/dashboard/@board/InitialContent.tsx
> +          description: message,
See the `types.ts` file comment

2024-03-06 20:04 UTC, tomivm commented on src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
> +                inputProps={{ minLength: 5, maxLength: 60 }}
@RodriSanchez1 Open an Issue to attend this separately.

2024-03-06 23:09 UTC, merged