Add circleci configuration file
cboard-org/cboard-ai-builder pull request #87
Opened 2024-03-09 05:40 UTC by martinbedouret

2024-03-11 17:31 UTC, RodriSanchez1 requested changes
LGTM! 
What do you think that we need to do with the docker compose?. Its located in docker folder.  We can added on this circleci confing?

2024-03-11 17:31 UTC, RodriSanchez1 commented on .circleci/config.yml
> +      - image: circleci/mongo:4.0
Why did you import the `mongo` image?

2024-03-11 17:31 UTC, RodriSanchez1 commented on .circleci/config.yml
> +          docker build -t cboard/cboard-ai-builder:$TAG -t cboard/cboard-ai-builder:latest .
What if  we use:
`docker build -t cboard/cboard-ai-builder:$TAG -t cboard/cboard-ai-builder:latest -f ./docker/Dockerfile .`

In this command, -f ./docker/Dockerfile tells Docker to use the Dockerfile in the ./docker directory, and . sets the build context to the root project directory. This means that COPY and ADD commands in the Dockerfile will be relative to the root project directory, not the ./docker directory.  - From ChatGPT

And with this, we can leave the `DockerFile` inside the docker folder

2024-03-11 17:31 UTC, RodriSanchez1 commented on Dockerfile
See above comment

2024-03-14 18:54 UTC, maxicapodacqua requested changes

2024-03-14 18:54 UTC, maxicapodacqua commented on .circleci/config.yml
> +      - run: yarn install --cache-folder ~/.cache/yarn
I'm not sure if this is needed, the docker image is already running `yarn install`

2024-03-14 18:54 UTC, maxicapodacqua commented on Dockerfile
This will break the current docker compose file, consider updating it or update the circleci to use the current directory

2024-03-19 00:20 UTC, merged