Feature/persist the store
cboard-org/cboard-ai-builder pull request #99
Opened 2024-03-12 18:43 UTC by tomivm

Persist the Zustand store using the Zustand persist middleware
Adapt the board UI to show a loader during hydration

2024-03-13 16:31 UTC, RodriSanchez1 requested changes
The prompt Form its blinking after change the prompt and press the NEW BOARD button. I think that is not an excepected behaviour

2024-03-13 16:31 UTC, RodriSanchez1 commented on src/stores/board-slice.ts
I noticed the variable names `showInitialContent` and `displayInitialContent`, and I believe renaming them could enhance clarity and maintainability in our codebase.

`displayInitialContent`: This variable's name suggests an action to display content, but it actually represents a boolean state. To accurately reflect its purpose, consider renaming it to something like `isInitialContentVisible` or `initialContentVisible`. By renaming it, we make it clear that this boolean variable represents the visibility state of the initial content.

`showInitialContent`: Similarly, this variable name could be more descriptive. Renaming it to `setInitialContentVisible` or `toggleInitialContentVisibility` would clarify its role in setting the visibility state of the initial content.

Choosing more descriptive variable names can help reduce ambiguity and make our codebase easier to understand for both current and future developers. - CHAT GPT

2024-03-13 16:31 UTC, RodriSanchez1 commented on src/providers/StoreProvider.tsx
Well donee!

2024-03-13 23:37 UTC, tomivm commented on src/stores/board-slice.ts
Good approach! I renamed `displayInitialContent` to `shouldDisplayInitialContent`. 
`ShowInitialContent` is an action to show the initial content. It makes sense to me

2024-03-13 23:44 UTC, tomivm commented
> The prompt Form its blinking after change the prompt and press the NEW BOARD button. I think that is not an excepected behaviour

Yes! it's not an expected behavior. I'm preparing a PR to convert the entire prompt form to a controlled component. see: #100.

2024-03-13 23:45 UTC, tomivm commented
Closed by error

2024-03-13 23:51 UTC, merged

2024-03-14 05:07 UTC, tomivm commented
> The prompt Form its blinking after change the prompt and press the NEW BOARD button

@RodriSanchez1 this problem is solved on #101